[2025-07-24T05:28:08.773+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bis_pipeline_dag.collect_bronze scheduled__2025-07-24T04:00:00+00:00 [queued]>
[2025-07-24T05:28:08.779+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bis_pipeline_dag.collect_bronze scheduled__2025-07-24T04:00:00+00:00 [queued]>
[2025-07-24T05:28:08.779+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-07-24T05:28:08.820+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): collect_bronze> on 2025-07-24 04:00:00+00:00
[2025-07-24T05:28:08.823+0000] {standard_task_runner.py:60} INFO - Started process 216 to run task
[2025-07-24T05:28:08.826+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'bis_pipeline_dag', 'collect_bronze', 'scheduled__2025-07-24T04:00:00+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/bis_pipeline_dag.py', '--cfg-path', '/tmp/tmpfpn5aw18']
[2025-07-24T05:28:08.828+0000] {standard_task_runner.py:88} INFO - Job 2: Subtask collect_bronze
[2025-07-24T05:28:08.903+0000] {task_command.py:423} INFO - Running <TaskInstance: bis_pipeline_dag.collect_bronze scheduled__2025-07-24T04:00:00+00:00 [running]> on host 4e9539c84d65
[2025-07-24T05:28:09.045+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='bis_pipeline_dag' AIRFLOW_CTX_TASK_ID='collect_bronze' AIRFLOW_CTX_EXECUTION_DATE='2025-07-24T04:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-24T04:00:00+00:00'
[2025-07-24T05:28:09.046+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-07-24T05:28:09.046+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /producer/api_producer.py']
[2025-07-24T05:28:09.053+0000] {subprocess.py:86} INFO - Output:
[2025-07-24T05:28:06.291+0000] {subprocess.py:93} INFO - python: can't open file '/producer/api_producer.py': [Errno 2] No such file or directory
[2025-07-24T05:28:06.293+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2025-07-24T05:28:06.302+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-07-24T05:28:06.304+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=bis_pipeline_dag, task_id=collect_bronze, execution_date=20250724T040000, start_date=20250724T052808, end_date=20250724T052806
[2025-07-24T05:28:06.369+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 2 for task collect_bronze (Bash command failed. The command returned a non-zero exit code 2.; 216)
[2025-07-24T05:28:06.389+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-07-24T05:28:06.404+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-24T05:58:23.152+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bis_pipeline_dag.collect_bronze scheduled__2025-07-24T04:00:00+00:00 [queued]>
[2025-07-24T05:58:23.157+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bis_pipeline_dag.collect_bronze scheduled__2025-07-24T04:00:00+00:00 [queued]>
[2025-07-24T05:58:23.157+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-07-24T05:58:23.198+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): collect_bronze> on 2025-07-24 04:00:00+00:00
[2025-07-24T05:58:23.203+0000] {standard_task_runner.py:60} INFO - Started process 191 to run task
[2025-07-24T05:58:23.205+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'bis_pipeline_dag', 'collect_bronze', 'scheduled__2025-07-24T04:00:00+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/bis_pipeline_dag.py', '--cfg-path', '/tmp/tmplziqu0ws']
[2025-07-24T05:58:23.207+0000] {standard_task_runner.py:88} INFO - Job 2: Subtask collect_bronze
[2025-07-24T05:58:23.278+0000] {task_command.py:423} INFO - Running <TaskInstance: bis_pipeline_dag.collect_bronze scheduled__2025-07-24T04:00:00+00:00 [running]> on host e9ea48abe9b7
[2025-07-24T05:58:23.414+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='bis_pipeline_dag' AIRFLOW_CTX_TASK_ID='collect_bronze' AIRFLOW_CTX_EXECUTION_DATE='2025-07-24T04:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-24T04:00:00+00:00'
[2025-07-24T05:58:23.414+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-07-24T05:58:23.415+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /producer/api_producer.py']
[2025-07-24T05:58:23.420+0000] {subprocess.py:86} INFO - Output:
[2025-07-24T05:58:23.493+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-07-24T05:58:23.493+0000] {subprocess.py:93} INFO -   File "/producer/api_producer.py", line 3, in <module>
[2025-07-24T05:58:23.493+0000] {subprocess.py:93} INFO -     from kafka import KafkaProducer
[2025-07-24T05:58:23.493+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'kafka'
[2025-07-24T05:58:23.503+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-07-24T05:58:23.511+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-07-24T05:58:23.513+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=bis_pipeline_dag, task_id=collect_bronze, execution_date=20250724T040000, start_date=20250724T055823, end_date=20250724T055823
[2025-07-24T05:58:23.547+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 2 for task collect_bronze (Bash command failed. The command returned a non-zero exit code 1.; 191)
[2025-07-24T05:58:23.594+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-07-24T05:58:23.611+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
