[2025-07-24T09:21:11.052+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bis_pipeline_dag.kafka_to_bronze manual__2025-07-24T09:21:08.237207+00:00 [queued]>
[2025-07-24T09:21:11.057+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bis_pipeline_dag.kafka_to_bronze manual__2025-07-24T09:21:08.237207+00:00 [queued]>
[2025-07-24T09:21:11.057+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-07-24T09:21:11.094+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): kafka_to_bronze> on 2025-07-24 09:21:08.237207+00:00
[2025-07-24T09:21:11.097+0000] {standard_task_runner.py:60} INFO - Started process 199 to run task
[2025-07-24T09:21:11.099+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'bis_pipeline_dag', 'kafka_to_bronze', 'manual__2025-07-24T09:21:08.237207+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/bis_pipeline_dag.py', '--cfg-path', '/tmp/tmprnjvs2iz']
[2025-07-24T09:21:11.101+0000] {standard_task_runner.py:88} INFO - Job 8: Subtask kafka_to_bronze
[2025-07-24T09:21:11.164+0000] {task_command.py:423} INFO - Running <TaskInstance: bis_pipeline_dag.kafka_to_bronze manual__2025-07-24T09:21:08.237207+00:00 [running]> on host 524d85ebccb4
[2025-07-24T09:21:11.268+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='bis_pipeline_dag' AIRFLOW_CTX_TASK_ID='kafka_to_bronze' AIRFLOW_CTX_EXECUTION_DATE='2025-07-24T09:21:08.237207+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-24T09:21:08.237207+00:00'
[2025-07-24T09:21:11.378+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/app/bronze.py", line 27, in kafka_to_bronze
    .getOrCreate()
  File "/home/airflow/.local/lib/python3.10/site-packages/pyspark/sql/session.py", line 556, in getOrCreate
    sc = SparkContext.getOrCreate(sparkConf)
  File "/home/airflow/.local/lib/python3.10/site-packages/pyspark/core/context.py", line 523, in getOrCreate
    SparkContext(conf=conf or SparkConf())
  File "/home/airflow/.local/lib/python3.10/site-packages/pyspark/core/context.py", line 205, in __init__
    SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
  File "/home/airflow/.local/lib/python3.10/site-packages/pyspark/core/context.py", line 444, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)
  File "/home/airflow/.local/lib/python3.10/site-packages/pyspark/java_gateway.py", line 111, in launch_gateway
    raise PySparkRuntimeError(
pyspark.errors.exceptions.base.PySparkRuntimeError: [JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.
[2025-07-24T09:21:11.386+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=bis_pipeline_dag, task_id=kafka_to_bronze, execution_date=20250724T092108, start_date=20250724T092111, end_date=20250724T092111
[2025-07-24T09:21:11.427+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 8 for task kafka_to_bronze ([JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.; 199)
[2025-07-24T09:21:11.432+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-07-24T09:21:11.447+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
